=== Mokshh7/Perl_Practice/FileHandling/data/employees.dtd
<!ELEMENT employees (employee+)>

<!ELEMENT employee (id, name, department, salary, status)>

<!ELEMENT id (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT department (#PCDATA)>
<!ELEMENT salary (#PCDATA)>
<!ELEMENT status (#PCDATA)>

=== Mokshh7/Perl_Practice/FileHandling/data/employees.xml
<!DOCTYPE employees SYSTEM "employees.dtd">
<employees>
    <employee>
        <id>101</id>
        <name>Aman</name>
        <department>IT</department>
        <salary>65000</salary>
        <status>active</status>
    </employee>

    <employee>
        <id>102</id>
        <name>Aman</name>
        <department>IT</department>
        <salary>65000</salary>
        <status>active</status>
    </employee>
</employees>
